# Truthy (Verdadero)
print(bool(True))
print(bool("Hello"))
print(bool(15))
print(bool(-16))
print(bool(2.5))
print(bool(.6))
print(bool([1, 2]))
print(bool((1, 2)))
print(bool({1, 2}))

# Falsey (Falso)
print(bool(False))
print(bool(""))
print(bool(0))
print(bool(0.0))
print(bool({}))
print(bool([]))
print(bool(()))